name: "Publish"
on: [push, workflow_dispatch]
jobs:
  build:
    name: "Build Package"
    runs-on: ubuntu-latest

    steps:
      # Setup Miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - run: |
          conda install conda-build anaconda-client

      - name: Checkout repository
        uses: actions/checkout@v3

      # Build and upload
      - name: Build package
        run: |
          conda build --output-folder .build .conda
          ls -R .build
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u ${{ env.ANACONDA_USER }} --all .build/noarch/sasctl-*.tar.bz2



