name: "Publish"
on: [push, workflow_dispatch]
jobs:
  build:
    name: "Build Package"
    runs-on: ubuntu-latest

    steps:
      # Setup Miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          conda-build-version: 3.23.3

      - name: Install conda-build
        run: |
          conda install conda-build

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build package
        run: |
          conda build .conda
          ls -R
