name: "Publish"
on: [push, workflow_dispatch]
jobs:

  build_conda:
    name: "Build Conda Package"
    runs-on: ubuntu-latest

    steps:
      # Setup Miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      - name: Installed conda-build and anaconda client
        shell: bash -l {0}
        run: |
          conda install conda-build anaconda-client

      - name: Checkout repository
        uses: actions/checkout@v3

      # Build and upload
      - name: Build package
        shell: bash -l {0}
        run: |
          conda build --output-folder .build .conda

      - name: Archive distribution artifacts
        # Archive distribution files for use by auto (or manual) PyPI upload
        uses: actions/upload-artifact@v3
        with:
          name: conda-dist
          path: .build


  upload_conda:
    name: "Upload Conda Package"
    runs-on: ubuntu-latest
    needs: [build_conda]

    steps:
      # Setup Miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      # Setup Anaconda client (required for upload)
      - name: Install anaconda client
        shell: bash -l {0}
        run: |
          conda install anaconda-client

      # Download release files
      - name: Download release
        uses: actions/download-artifact@v3
        with:
          name: conda-dist
          path: ./dist

      # Upload release to Anaconda.org
      - name: Upload release
        shell: bash -l {0}
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u jlwalke2 ./dist/noarch/sasctl-*.tar.bz2